blog/apps/noticias/urls.py
from django.urls import path
from . import views

app_name = "noticias"

# urls de app noticias
urlpatterns = [
    path("", views.inicio, name= "inicio"),


]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include                
from apps.noticias import views
from . import views

# URL PRINCIPAL
urlpatterns = [
    path('admin/', admin.site.urls),
    # path para la view
    path("", views.home, name="home"),
    # path para nosotros
    path("nosotros/", views.nosotros, name="nosotros"),

    # ---------URL APP NOTICIAS------------------
    path("noticias/", include('apps.noticias.urls')),
]

blog/apps/noticias/models.py
from django.db import models

# Create your models here.

blog/apps/usuarios/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    pass

blog/apps/noticias/views.py
from django.shortcuts import render

# Create your views here.
def inicio(request):
    return render(request, "noticias/inicio.html")

blog/apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.

blog/blog/views.py
from django.shortcuts import render

def home(request):
    return render(request, "home.html")

def nosotros(request):
    return render(request, "nosotros.html")

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Blog/ {% block titulo %} {% endblock titulo %}</title>
</head>
<body class="contenedor">
    <div> 
        <a href="{% url 'home' %}"> template home</a> 
        <a href="{% url 'nosotros' %}"> template nosotros</a>
        <a href="{% url 'noticias:inicio' %}"> template noticias</a> 
    </div>
    {% block contenido %} 
    
    {% endblock contenido %}
    
   
    

</body>
</html>

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}

{%block titulo%} HOME {%endblock titulo%}

{%block contenido%}
    <img src= {% static 'img/im.jpg' %} alt="error" height="250px">
    <h1>Este es el inicio de nuestro Blog</h1>
{%endblock contenido%}    

blog/templates/nosotros.html
{% extends 'base.html' %}
{% load static %}

{%block titulo%} NOSOTROS {%endblock titulo%}

{%block contenido%}
<h1> nosotros somos: </h1>
<h2>El grupo 9</h2>
<h1>Alarcon Fabricio, Carlos Eduardo Gómez, Juan Manuel Castella, Alan Quenardelle </h1>
{%endblock contenido%}    

blog/templates/noticias/inicio.html
{% extends 'base.html' %}
{% load static %}

{%block titulo%} NOTICIAS {%endblock titulo%}

{%block contenido%}
    <h1>noticias</h1>
    <h3>Estudiar programación es algo más que sacar una buena nota</h3>
    <img src=https://www.enter.co/wp-content/uploads/2022/02/pexels-christina-morillo-1181673-768x432.jpg alt="error" height="250px">
    <p> Si hay alguna profesión que esté de moda es el desarrollo web- Mientras que otras carreras tienen vacantes esporádicas y ofrecen pocas oportunidades reales de crecimiento, hay una demanda enorme por más expertos en desarrollo de software. El problema está cuando ya tiene una carrera, un trabajo, unas responsabilidades y también el interés en aprender algo nuevo: ¿Es posible estudiar programación  mientras que se está trabajando?</p>


        <p>En ENTER.CO hablamos con Sebastián Gonzales, un caleño de 30 años que trabaja como profesional administrativo/operativo en el área de mantenimiento de equipos biomedicos y hace poco menos de un año decidió ingresar al programa de Holberton School. Una de las cosas que más nos llamó la atención de su historia es el hecho de que, incluso con un trabajo a tiempo completo y la carga que supone las sesiones y proyectos de Holberton, Sebastían ha logrado mantener un promedio de 138.</p>
    
            <p>Pero, a pesar de esto, Sebastían asegura que lo más importante de su proceso en Holberton es que en al momento de estudiar programación, contrario a lo que ocurre en la academia tradicional, las notas son lo de menos. En vez de esto, está en que la principal lección es el ‘aprender a aprender’ (una habilidad que repiten sin descansar los reclutadores de las compañías más grandes de tecnología). “Cuando yo terminé con el programa, más que unos conocimientos específicos, creo que lo que me llevó es la capacidad de seguir aprendiendo por mi cuenta. De buscar o utilizar las herramientas que descubrí”.</p>
    
                <p>Como la mayoría de personas que deciden dar el salto a aprender programación, Sebastían no teme reconocer que lo que inicialmente lo motivó a estudiar fue la anécdota de la familiar de una compañera de trabajo que había pasado por el programa y ahora tenía un trabajo con un salario bastante atractivo. “Mis otros compañeros me decían que por qué no me había dedicado a la programación… y yo dije intentemos”.</p>

{%endblock contenido%}    